#!/usr/bin/env bash
# Generates ios/SitePhoto/Generated/BuildInfo.swift with the current
# git SHA + UTC timestamp.
#
# Called by `ios/scripts/regen-project.sh` immediately before
# `xcodegen generate`, so every project regeneration embeds fresh
# build info. The generated Swift file is gitignored.
#
# Why generate at xcodegen time (instead of Xcode build time):
# Xcode 15+ enables user-script sandboxing, which blocks build-phase
# scripts from running `git`. Running git here, before Xcode is
# involved, sidesteps the sandbox entirely. The trade-off: build
# info reflects what `xcodegen` last saw, not the live working tree.
# Re-run `regen-project.sh` after a pull or commit to refresh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IOS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${IOS_DIR}/.." && pwd)"

OUT_DIR="${IOS_DIR}/SitePhoto/Generated"
OUT_FILE="${OUT_DIR}/BuildInfo.swift"

mkdir -p "${OUT_DIR}"

GIT_SHA="$(cd "${REPO_ROOT}" && git rev-parse --short=8 HEAD 2>/dev/null || echo dev)"
GIT_BRANCH="$(cd "${REPO_ROOT}" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo dev)"
BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Build number from `docs/builds/` — one file per build, named
# `N.M.P.md`. Take the version-sorted maximum filename and strip
# the `.md` extension. Returns empty string when the directory
# doesn't exist or is empty (older worktrees pre-Build-1). Format
# is dotted-decimal (e.g. `1.1.4`); see `docs/builds.md` for the
# scheme.
BUILDS_DIR="${REPO_ROOT}/docs/builds"
BUILD_NUMBER=""
if [ -d "${BUILDS_DIR}" ]; then
    BUILD_NUMBER="$(cd "${BUILDS_DIR}" && ls -1 *.md 2>/dev/null \
                    | sed 's/\.md$//' \
                    | sort -t. -k1,1n -k2,2n -k3,3n \
                    | tail -1 \
                    || echo "")"
fi

cat > "${OUT_FILE}" <<EOF
// Auto-generated by ios/scripts/gen-build-info.sh on every
// xcodegen run. DO NOT EDIT — your changes will be overwritten.

enum BuildInfo {
    /// Short git SHA of the commit checked out when xcodegen ran.
    /// "dev" if git wasn't available (rare).
    static let gitSHA = "${GIT_SHA}"

    /// Branch name from \`git rev-parse --abbrev-ref HEAD\`.
    /// "HEAD" when in a detached-HEAD checkout (e.g. CI builds
    /// from a specific commit).
    static let gitBranch = "${GIT_BRANCH}"

    /// UTC timestamp of the most recent xcodegen run, ISO-8601.
    static let buildTime = "${BUILD_TIME}"

    /// Sequential build number — version-sorted maximum
    /// filename in \`docs/builds/\`. Empty string when the
    /// directory doesn't exist or is empty (older worktrees
    /// pre-Build-1). See \`docs/builds.md\` for the
    /// number-to-commit registry layout.
    static let buildNumber = "${BUILD_NUMBER}"

    /// Single-string display for UI surfaces — used by the
    /// Settings sheet's "About" row.
    /// Example: "#1 · main@bf3e15ab · 2026-05-28T05:42:00Z"
    static let display: String = {
        let prefix = "${BUILD_NUMBER}".isEmpty ? "" : "#${BUILD_NUMBER} · "
        return "\(prefix)${GIT_BRANCH}@${GIT_SHA} · ${BUILD_TIME}"
    }()
}
EOF

echo "gen-build-info: wrote ${OUT_FILE} (build #${BUILD_NUMBER:-?}, ${GIT_BRANCH}@${GIT_SHA})"
